// <auto-generated />
using System;
using CF.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CF.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240527173818_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Extensions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d71f88c-e8ec-4c2d-9b7c-9a9bade489b9"),
                            AuthorId = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            CreationTime = new DateTime(2024, 5, 27, 17, 38, 17, 188, DateTimeKind.Utc).AddTicks(7998),
                            Description = "Gost is a simple, fast and reliable charting library.",
                            IsRemoved = false,
                            Name = "Gost"
                        },
                        new
                        {
                            Id = new Guid("ee769dbc-df94-414e-9da3-620bced768fb"),
                            AuthorId = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            CreationTime = new DateTime(2024, 5, 27, 17, 38, 17, 188, DateTimeKind.Utc).AddTicks(8019),
                            Description = "Helper for grid movement.",
                            IsRemoved = false,
                            Name = "Grid movement helper"
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionComments", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionUsing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivationTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeactivationTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionUsings", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<short>("PeriodInDays")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 9.99m,
                            EndTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1 month",
                            PeriodInDays = (short)30,
                            StartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Cost = 99.99m,
                            EndTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "12 months",
                            PeriodInDays = (short)365,
                            StartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastOnlineTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("PasswordSaltedHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            Email = "chartflow@yandex.by",
                            LastOnlineTime = new DateTime(2024, 5, 27, 17, 38, 17, 259, DateTimeKind.Utc).AddTicks(7958),
                            Login = "chartflow",
                            PasswordSalt = new byte[] { 189, 86, 206, 210, 121, 138, 27, 48, 98, 255, 195, 191, 138, 215, 98, 71 },
                            PasswordSaltedHash = new byte[] { 218, 27, 125, 229, 89, 36, 119, 213, 218, 176, 137, 30, 176, 216, 184, 81, 177, 22, 106, 107, 83, 154, 46, 139, 190, 139, 190, 162, 198, 33, 197, 211 }
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.HasOne("CF.Web.Data.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionComment", b =>
                {
                    b.HasOne("CF.Web.Data.Models.Extension", "Extension")
                        .WithMany("Comments")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionUsing", b =>
                {
                    b.HasOne("CF.Web.Data.Models.Extension", "Extension")
                        .WithMany("Usings")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.Subscription", b =>
                {
                    b.HasOne("CF.Web.Data.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Usings");
                });
#pragma warning restore 612, 618
        }
    }
}
