// <auto-generated />
using System;
using CF.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CF.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Extensions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bdf8ce8-0761-4553-8a6e-0e24779ae097"),
                            AuthorId = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            CreationTime = new DateTime(2024, 6, 6, 17, 15, 41, 40, DateTimeKind.Utc).AddTicks(8966),
                            Description = "Gost is a simple, fast and reliable charting library.",
                            IsRemoved = false,
                            Name = "Gost"
                        },
                        new
                        {
                            Id = new Guid("a9345d74-67f1-4a29-afc8-6950cd28b9d5"),
                            AuthorId = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            CreationTime = new DateTime(2024, 6, 6, 17, 15, 41, 40, DateTimeKind.Utc).AddTicks(8972),
                            Description = "Use case diagram with actor and actions.",
                            IsRemoved = false,
                            Name = "Use Case"
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionComments", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionUsing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivationTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeactivationTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExtensionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtensionUsings", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("CF.Web.Data.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<short>("PeriodInDays")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 9.99m,
                            EndTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1 month",
                            PeriodInDays = (short)30,
                            StartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Cost = 99.99m,
                            EndTime = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "12 months",
                            PeriodInDays = (short)365,
                            StartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastOnlineTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<byte[]>("PasswordSaltedHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("396f400a-2c1a-4cd0-9323-df2d02770833"),
                            Email = "chartflow@yandex.by",
                            LastOnlineTime = new DateTime(2024, 6, 6, 17, 15, 41, 126, DateTimeKind.Utc).AddTicks(1797),
                            Login = "chartflow",
                            PasswordSalt = new byte[] { 243, 26, 189, 39, 251, 178, 246, 149, 214, 83, 121, 42, 235, 71, 130, 158 },
                            PasswordSaltedHash = new byte[] { 66, 136, 181, 162, 70, 68, 2, 124, 32, 239, 172, 229, 110, 235, 58, 155, 75, 235, 56, 103, 169, 36, 225, 192, 31, 157, 74, 91, 47, 126, 213, 143 }
                        });
                });

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.HasOne("CF.Web.Data.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionComment", b =>
                {
                    b.HasOne("CF.Web.Data.Models.Extension", "Extension")
                        .WithMany("Comments")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.ExtensionUsing", b =>
                {
                    b.HasOne("CF.Web.Data.Models.Extension", "Extension")
                        .WithMany("Usings")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Extension");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.Subscription", b =>
                {
                    b.HasOne("CF.Web.Data.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CF.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CF.Web.Data.Models.Extension", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Usings");
                });
#pragma warning restore 612, 618
        }
    }
}
